### PR TITLE
made transit.types.UUID/-hash compatible with cljs.core.UUID/-hash

### PR DESCRIPTION
**Pull request by tonsky**
`(hash #uuid "550e8400-e29b-41d4-a716-446655440000")` => 4112693013
`(hash (t/read r "{\"~#'\":\"~u550e8400-e29b-41d4-a716-446655440000\"}")))` => 1716781005

Problem is that one relies on `(hash (pr-str uuid))` while other on `(hash (str uuid))`

### CODE REVIEW

**Comment by swannodette** [comment]
This project doesn't take pull requests, but this is easy enough to fix. I'll look into it.

**Comment by tonsky** [comment]
BTW why don’t just use `cljs.core/UUID` for `#uuid` tag in transit-cljs?

**Comment by swannodette** [comment]
@tonsky `cljs.core/UUID` has less functionality than the `UUID` type supplied by transit-js

**Comment by tonsky** [comment]
Right, but it’s not available to CLJS users anyway. And it complicates things a lot in a most harmful way: by trying to look like cljs.core/UUID. So suddenly one UUID is not equal to another. Or one UUID is not comparable to another. Or I extend cljs.core/UUID with my protocol and it doesn’t work sometimes. It’s really hard to debug, because this subtle difference comes from uuid origin: if it had roundtrip to server or not. It really seems like not that good of an idea. Also equailty, hash and toString are faster between two cljs.core/UUIDs than between mix of transit-js and cljs.core UUIDs.

It’s just my opinion, but please at least give it a round of thoughts. Maybe decision to introduce second type for already existing thing may be reconsidered.

Thanks for the Transit btw, it really rocks!

**Comment by swannodette** [comment]
@tonsky it's not going to change. 

The enhanced `UUID` is what you get if you use transit-cljs.

As far as any existing issues, file each bug you encounter and it will get addressed.

**Comment by tonsky** [comment]
@swannodette is it because it might affect existing clients? Wouldn’t they prefer speed and simplicity over breaking change?

**Comment by swannodette** [comment]
@tonsky as I said it's not going to change. File issues for bugs and requests for perf enhancements. These are all trivial things for me to do. I've said as much as I'm going to say about this issue. Thanks.

**Comment by tonsky** [comment]
Ok, understood. I think I know what you’re talking about.

Just for future reference, if somebody else comes along:
```
(transit/read (transit/reader :json {:handlers {"u" ->UUID}}) str)
```
fixes most of the issues by binding `cljs.core/UUID` to `#uuid` tag. You’ll never see `com.cognitect.transit.types/UUID` in your programs anymore :)

**Comment by tonsky** [comment]
Please note that this change might not be needed if http://dev.clojure.org/jira/browse/CLJS-1256 gets merged into CLJS

**Comment by danielcompton** [comment]
I was caught out by this as well today. What do you think about adding something to the README explicitly pointing out that transit-cljs returns a cct UUID, not a cc UUID?

Or is this not an issue in CLJS versions after 3297?

**Comment by tonsky** [comment]
@danielcompton this commit changes CLJS UUID hash to be the same transit-js hash is: https://github.com/clojure/clojurescript/commit/bc4f3b5930c7f02f062beffa5ca1f8c8206ecb5c

It is included in 3291 and up.

Although it does fix a hash, they are still 2 different types, so if you’re extending, you have to extend both, compare doesn’t work (#11), etc.

I recommend use `(transit/read (transit/reader :json {:handlers {"u" cljs.core/uuid}}) str)` to get native UUIDs. Just much less pain

**Comment by yatesco** [comment]
@swannodette - please read this from me as a very grateful consumer of Clojure and ClojureScript.

This caught me out as well and for what its worth I too think this is a bad decision. If there is something insufficient in `cljs.core/UUID` then surely the right thing to do is fix `cljs.core/UUID`? You (Cognitect) are the guardians of both this and ClojureScript aren't you? All of a sudden the types I am using throughout my code base are defined by the library whose responsibility is moving things over a wire? If that isn't a leak of responsibility/inappropriate coupling then what is? And the fact it is fairly trivially fixable by adding a handler is neither here nor there - libraries should do the right thing by default and optionally allow bad behaviour.

My understanding (although I don't see it explicitly anywhere) was that transit was going to be fairly transparent, at the very least it should obey the laws of 'least surprise' - suddenly using a whole new and incompatible type for an existing type is a decision whose rationale we are just supposed to swallow?

@swannodette I realise it your prerogative to respond with "it's not going to change" and "I've said as much as I'm going to say about this issue" but you must realise that the effect of this is from outside (well, my POV anyway) it makes it look like arbitrary and disruptive changes are being made without thought or consideration to existing users. It also comes across as a little as a 'tough, suck it up' attitude. That is _very_ troubling.

I am troubled writing this because I feel like this is an exemplar of 'teaching to suck eggs' but I am really quite concerned by what I see here. This isn't the greatest behaviour for any open source library, particularly a key one in the Clojure/ClojureScript eco-system and frankly I am surprised and concerned by the fracture, the inconsistency between ClojureScript and transit and the whole 'closed-door'-ness attitude.

(but still very appreciative of Clojure and ClojureScript :-)).

**Comment by muhuk** [comment]
`#(curtify %)`  |  `#(amiabilize %)`
-------------------|------------------------
It's not going to change  |  We're not considering changing this.
I've said as much as I'm going to say  |  I'm busy with other things, I won't be able to respond 

On @swannodette's defence he said:

> This project doesn't take pull requests, but this is easy enough to fix. I'll look into it.

... and this:

> file each bug you encounter and it will get addressed.

... and this:

> File issues for bugs and requests for perf enhancements. 

I think the reason he might not want to continue the discussion here is because they prefer jira and they'd like everything to be archived there.

I guess there is no way to turn off pull requests on GH.

**Comment by mike-thompson-day8** [comment]
@yatesco +1

**Comment by swannodette** [comment]
This would be introducing a breaking change of long existing well documented behavior in a now heavily depended on library. Would need more feedback (not in this closed issue) before making any decision.

**Comment by niwinz** [comment]
@yatesco  +1

**Pull request closed without merging**
